DROP TABLE IF EXISTS user_info CASCADE;
DROP TABLE IF EXISTS artist_info CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TYPE app_visitor_role;
